server {
    listen       80;
    listen  [::]:80;
    server_name daves.local;

    location / {
	    #rewrite ^/fe(/.*)$ $1 break;
            proxy_pass http://192.168.0.47:8081/;
	     proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api {
	    proxy_pass http://daves.local:4004/api;
	     proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
