spring.application.name=holiday

#spring.mongodb.uri=mongodb://admin:admin@localhost:27018/movinin
spring.mongodb.host=localhost
spring.mongodb.authentication-database=admin
spring.mongodb.port=27018
spring.mongodb.database=movinin
spring.mongodb.username=admin
spring.mongodb.password=admin